#!/bin/sh

./Hawkeyerunscript SPEC bzip2 Hawkeye
./Hawkeyerunscript SPEC gcc Hawkeye
./Hawkeyerunscript SPEC mcf Hawkeye
./Hawkeyerunscript SPEC hmmer Hawkeye
./Hawkeyerunscript SPEC sjeng Hawkeye
./Hawkeyerunscript SPEC libquantum Hawkeye
./Hawkeyerunscript SPEC xalancbmk Hawkeye
./Hawkeyerunscript SPEC milc Hawkeye
./Hawkeyerunscript SPEC cactusADM Hawkeye
./Hawkeyerunscript SPEC leslie3d Hawkeye
./Hawkeyerunscript SPEC namd Hawkeye
./Hawkeyerunscript SPEC soplex Hawkeye
./Hawkeyerunscript SPEC calculiz Hawkeye
./Hawkeyerunscript SPEC lbm Hawkeye
./Hawkeyerunscript PARSEC blackscholes Hawkeye
./Hawkeyerunscript PARSEC bodytrack Hawkeye
./Hawkeyerunscript PARSEC canneal Hawkeye
./Hawkeyerunscript PARSEC dedup Hawkeye
./Hawkeyerunscript PARSEC fluidanimate Hawkeye
./Hawkeyerunscript PARSEC freqmine Hawkeye
./Hawkeyerunscript PARSEC streamcluster Hawkeye
./Hawkeyerunscript PARSEC swaptions Hawkeye
./Hawkeyerunscript PARSEC x264 Hawkeye
