#!/bin/sh
./hw4runscript PARSEC blackscholes LFU
./hw4runscript PARSEC blackscholes LRU
./hw4runscript PARSEC bodytrack LFU


./hw4runscript SPEC bzip2 SRRIP
./hw4runscript SPEC gcc SRRIP
./hw4runscript SPEC mcf SRRIP
./hw4runscript SPEC hmmer SRRIP
./hw4runscript SPEC sjeng SRRIP
./hw4runscript SPEC libquantum SRRIP
./hw4runscript SPEC xalancbmk SRRIP
./hw4runscript SPEC milc SRRIP
./hw4runscript SPEC cactusADM SRRIP
./hw4runscript SPEC leslie3d SRRIP
./hw4runscript SPEC namd SRRIP
./hw4runscript SPEC soplex SRRIP
./hw4runscript SPEC calculiz SRRIP
./hw4runscript SPEC lbm SRRIP
./hw4runscript PARSEC blackscholes SRRIP
./hw4runscript PARSEC bodytrack SRRIP
./hw4runscript PARSEC canneal SRRIP
./hw4runscript PARSEC dedup SRRIP
./hw4runscript PARSEC fluidanimate SRRIP
./hw4runscript PARSEC freqmine SRRIP
./hw4runscript PARSEC streamcluster SRRIP
./hw4runscript PARSEC swaptions SRRIP
./hw4runscript PARSEC x264 SRRIP
