#!/bin/sh

./hw4runscript SPEC milc Hawkeye
./hw4runscript SPEC leslie3d Hawkeye
./hw4runscript PARSEC blackscholes Hawkeye
./hw4runscript PARSEC bodytrack Hawkeye
./hw4runscript PARSEC canneal Hawkeye
./hw4runscript PARSEC dedup Hawkeye
./hw4runscript PARSEC x264 Hawkeye